# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    

    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v2
      with:
       creds: ${{secrets.AZURE_CREDS}}
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
       node-version: '20.14.0'

    - name: Install Dependencies
      run: |
        npm install
        npm run dev
      working-directory: .

    - name: Deploy
      uses: azure/webapps-deploy@v3
      with:
        app-name: helloworldashish
        package: ./next

    - name: logout
      run:  |
          az logout
